### ISSUE TITLE
Can't find a suitable configuration file

### ISSUE THREAD

**Issue by RiRomain** [juanluisbaptiste/docker-bitcoin-wallet#1]
How should the wallet-data be created?

ERROR: Service "wallet" mounts volumes from "wallet-data", which is not the name of a service or container.

**Comment by juanluisbaptiste** [comment]
Ooops, I forgot to add the docker-compose.yml file. Just added it.

**Comment by juanluisbaptiste** [comment]
The wallet-data container is created automatically when the container is started up.
